# Generated by Django 3.2.8 on 2021-10-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'english'), ('de', 'german')], max_length=100, null=True),
        ),
    ]
