# Generated by Django 3.2.8 on 2021-10-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_detector', '0002_snippet_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'en'), ('german', 'de')], max_length=100, null=True),
        ),
    ]
