# Generated by Django 3.2.8 on 2021-10-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_detector', '0003_alter_snippet_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
